version: '3'

services:
  neo4j:
    image: neo4j:3.5
    container_name: wem-neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo4j-data:/data

  front:
    container_name: wem-front
    build:
      context: ./front
    volumes:
      - "./front/dist/front/:/usr/share/nginx/html/"
    ports:
      - 80:80

  back:
    container_name: wem-back
    build:
      context: ./back
    volumes:
      - "./back/app/:/app/"
    ports:
      - 5000:5000

volumes:
  neo4j-data:
